# Generated by Django 3.0.7 on 2020-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_type', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('img', models.ImageField(upload_to='pics')),
                ('guardian_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('course', models.CharField(max_length=40)),
                ('primary_num', models.CharField(max_length=40)),
                ('secondary_num', models.CharField(max_length=40)),
            ],
        ),
    ]
